name: Production Deployment

on: workflow_dispatch

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-compose-action@v1

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci

      - name: Stop cloud server
        env:
          DOCKER_HOST: ${{ vars.TAILSCALE_TARGET_HOST }}
        run: |
          docker compose -f docker-compose.prod.yml stop

      - name: Migrate Supabase schemas
        id: migrate-supabase-schemas
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push

      - name: Fallback cloud server
        if: steps.migrate-supabase-schemas.outcome == 'failure'
        env:
          DOCKER_HOST: ${{ vars.TAILSCALE_TARGET_HOST }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          WEB_URL: ${{ vars.WEB_URL }}
        run: |
          docker compose -f docker-compose.prod.yml start

      - name: Deploy to cloud
        env:
          DOCKER_HOST: ${{ vars.TAILSCALE_TARGET_HOST }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          WEB_URL: ${{ vars.WEB_URL }}
        run: |
          docker logout
          echo ${{ secrets.DOCKER_PAT }} | docker login ghcr.io -u ${{ GITHUB.repository_owner }} --password-stdin
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d
          docker logout
