name: Production Build

on:
  push:
  workflow_call:

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/setup-compose-action@v1

      - name: Spin-up API server
        env:
          DOCKER_IMAGE_TAG: ${{ github.ref_name }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          WEB_URL: ${{ vars.WEB_URL }}
        run: |
          docker compose -f docker-compose.prod.yml up api -d --build
          for i in {1..100}; do
              CONTAINER_ID=$(docker compose -f docker-compose.prod.yml ps -q api)
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_ID")
              echo "--- Logs (attempt $i) ($STATUS) ---"
              docker logs --tail 10 "$CONTAINER_ID"
              if [ "$STATUS" == "healthy" ]; then
              exit 0
              fi
              sleep 5
          done
          exit 1

      - name: Generate GraphQL codegen
        run: |
          npm install @graphql-codegen/cli @graphql-codegen/typescript-generic-sdk
          cd web
          npm run graphql-codegen:production

      - name: Build and Push Web Image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile.prod
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE_URL }}/web:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('{0}/web:latest', vars.DOCKER_IMAGE_URL) || '' }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE_URL }}/api:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('{0}/api:latest', vars.DOCKER_IMAGE_URL) || '' }}

  test:
    needs: build
    uses: ./.github/workflows/production.test.yml
    secrets: inherit
